// SAMPLE TEMPLE
export const UPDATE_CANINE = "UPDATE_CANINE";



// CART UI FOR DONANTIONS
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';
export const TOGGLE_CART = 'TOGGLE_CART';
